name: ci-process
on:
  pull_request:
    branches:
      - master

jobs:
  test-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test ./... -v